# -*- coding: utf-8 -*-
"""rayleigh_fading.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SkLehXffafvYxVb31SzypPqBm7astKDu
"""

import numpy as np
import matplotlib.pyplot as plt

N = 512
fd = [5.55, 70, 100]
L = 5
tau = np.array([0, 2, 8, 14, 20]) * 1e-6
pdb = np.array([0.5, 0.25, 0.2, 0.1, 0.05])
Ts = 2e-6
sampled_tau = (tau / Ts).astype(int)

epsilon = 1e-6
for jj, fm in enumerate(fd):
    df = (2 * fm) / (N - 1)
    f = np.linspace(-fm, fm, N)
    S = 1.5 / (np.pi * fm * np.sqrt(np.maximum(1 - (f / fm) ** 2, epsilon)))
    S[0] = 2 * S[1] - S[2]
    S[-1] = 2 * S[-2] - S[-3]

    gaussian_vari = np.random.randn(L) + 1j * np.random.randn(L)
    plt.plot(20 * np.log10(np.abs(np.fft.fft(gaussian_vari, N))), label=f'fd={fm} Hz')

plt.xlabel("Frequency Index")
plt.ylabel("Power Spectral Density (dB)")
plt.title("Power Spectral Density for Different Doppler Frequencies")
plt.legend()
plt.grid()
plt.show()